#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          audiosessionmanager
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start audio-session-manager daemon
### END INIT INFO


if [ -x /usr/bin/audio-session-mgr-server ]; then
	/usr/bin/audio-session-mgr-server &
fi
